### ISSUE TITLE
Epileptic bug on MacOS

### ISSUE THREAD

**Issue by ronangaillard** [danfragoso/thdwb#23]
I cloned your project and run `make` and I was left with this epileptic bug : 

![Apr-20-2021 12-23-23](https://user-images.githubusercontent.com/5607736/115380907-57508c00-a1d3-11eb-9fac-b5c2bef4ff3a.gif)

Maybe this has something to do with high DPI screens ?

Commit I used : `532f88c`

System info : 

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5607736/115381014-72bb9700-a1d3-11eb-8ff1-14c40dea8146.png">

**Comment by equalsraf** [comment]
I was seeing a similar issue in Linux/X11 with an intel card. 

I changed the hi-dpi value in settings.json to false, and was able to avoid the issue.

```json
  "hiDPI": false,
```

**Comment by dyaskur** [comment]
<img width="1601" alt="Screen Shot 1442-09-09 at 6 03 27 PANGERAN" src="https://user-images.githubusercontent.com/9539970/115474261-4cdfd200-a267-11eb-9e67-8697b017e346.png">

my settings.json:

```
{
  "homepage":"thdwb://homepage/",
  "windowWidth": 1600,
  "windowHeight": 900,

  "hiDPI": false,

  "experimentalHTML": false,
  "experimentalLayout": false
}
```

**Comment by montyanderson** [comment]
Also got this issue on Mac OS.

`"hiDPI": false` makes the window a little larger but still a small portion of the total window size.

**Comment by raff** [comment]
At least on MacOS it seems that when using hiDPI the scale is reversed. I.e. in https://github.com/danfragoso/thdwb/blob/master/mustard/window.go#L35:

`
        window := &Window{
                title:  title,
                width:  int(float32(width) / xscale),
                height: int(float32(height) / yscale),
                hiDPI:  hiDPI,
`
it should really be:

`
                width:  int(float32(width) * xscale),
                height: int(float32(height) * yscale),
`

That makes the window content fill the window (but then it goes back to small with flicker on resize, so I think the same needs to be done wherever the window resize code is).

**Comment by bigwhite** [comment]
I got this issue on Mac OS, too.

**Comment by ajzaff** [comment]
@raff That seems plausible for the scale issue. The resize callback is here: https://github.com/danfragoso/thdwb/blob/master/mustard/window.go#L139
I pushed the fix to my branch if anyone cares to try it? https://github.com/ajzaff/thdwb/tree/feature-content-scale-23

**Comment by danfragoso** [comment]
Hi, sorry for the delay, I've been really busy with work this couple of weeks. I fixed the scaling issue on linux with commit  088ec74, can you guys try it again?

@ronangaillard @dyaskur @montyanderson @raff @bigwhite @ajzaff

**Comment by dyaskur** [comment]
On my mac still has same result

<img width="903" alt="Screen Shot 1442-09-16 at 2 29 18 PANGERAN" src="https://user-images.githubusercontent.com/9539970/116300836-8b2a4380-a7c9-11eb-88b0-150f65f61b32.png">

**Comment by raff** [comment]
@dyaskur, if you applied https://github.com/ajzaff/thdwb/tree/feature-content-scale-23, make sure you have hiDPI=true in settings.json.

The fix is still not perfect (on resizes there are cases depending on the window size where the screen goes white) but mostly works.
